parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - prettier

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "warn", { allow: [ "error" ] } ]

  react/jsx-filename-extension: off
  react/prop-types: off
  react/react-in-jsx-scope: off
  react/jsx-curly-brace-presence: [ "warn", "never" ]

  "@typescript-eslint/no-loop-func": off
  "@typescript-eslint/no-namespace": off
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
      args: "all"
