parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier

rules:
  no-plusplus: [ "error", { "allowForLoopAfterthoughts": true } ]
  no-console: [ "warn", { allow: [ "error" ] } ]

  react/jsx-filename-extension: off

  "@typescript-eslint/no-loop-func": off
  "@typescript-eslint/no-namespace": off
